-- Modify the tic-tac-toe program to choose a random move 
-- from the list of best moves (Generated by minmax)
-- use the function randomRIO :: (Int, Int) -> IO Int from System.Random

import System.Random 
import Data.Char
import Data.List
import System.IO


-- Modify best move to return all best moves and then select a random one from the list
bestmove :: Grid -> Player -> Grid
bestmove g p = do rand <- randomRIO(0, length moves - 1 )
               where 
               	  moves = [g' | Node (g',p') _ <- ts, p' == best]
                  tree = prune depth (gametree g p)
                  Node (_,best) ts = minimax tree

