-- Using the function gametree verify that there are
-- 549,946 nodes in the complete game tree for 
-- a 3x3 tic-tac-toe game, starting from the empty grid
-- and that the maximum depth of this tree is 9